#cloud-config
packages:
  - docker

runcmd:
  - usermod -a -G docker ec2-user
  - service docker start
  - IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4) && docker run -d --net=host --name=consul consul agent -server -ui -bind="$IP" -client="0.0.0.0" -retry-join-ec2-tag-key="aws:autoscaling:${asgname}" -retry-join-ec2-region="${region}" -retry-join-ec2-tag-value="ops-cluster" -bootstrap-expect="${size}"
